print("    *     ")
print("   ***    ")
print("  *****   ")
print(" *******  ")
print("**********")


print("     x    ")
print("    xxx   ")
print("   xxxxx  ")
print("  xxxxxxx ")
print(" xxxxxxxxx")
print("  xxxxxxx ")
print("    xxxx  ")
print("      x   ")