print("hello sharon")
print("hello sharon")
print ("i love watching")
print ( "i like swimming")
print ("i love travelling")
print("*")
print("**")
print("***")
print("****")
print("*****")
print("********************")
print("sharon")
print("**********************************")